Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,17 +45,22 @@ jobs:
       with:
         flutter-version: ${{ env.FLUTTER_VERSION }}
 
+    - name: Install Missing Dependencies
+      run: |
+        sudo apt update
+        sudo apt install -y ninja-build libgtk-3-dev
+
     - name: Verify Flutter Installation
       run: flutter --version
 
     - name: Verify Flet Installation
       run: flet --version
 
-    - name: Flet Build Web
+    - name: Debug Flet Build
       run: |
         echo "Building the web project..."
         flutter config --no-analytics
-        flet build web --module-name main
+        flet build web --module-name main || echo "Flet build failed with exit code $?"
 
     - name: List Build Directory
       run: ls -la build/web
